### PR TITLE
Allow dynamic CORS headers

### PR DESCRIPTION
**Pull request by rgala**
Extended CORS plugin to allow setting of **Access-Control-Allow-Origin** dynamically by matching Origin header with regular expressions.

### CODE REVIEW

**Comment by m1h43l** [comment]
We need to support at least 7.3 (perhaps even 7.2 , @NielsLiisberg ? ). The code uses some features which were introduced in 7.4 , namely auto sized arrays, snd-msg and procedure overloading.

- corsConfigurations array dim(*auto)  - alternative : use an extra variable for storing the number of elements
- %elem on the left hand side of an expression is not allowed
- snd-msg
- overloading is not supported in 7.2/7.3 (out-of-the-box) : 7.4, TR1 or 7.3 TR7 , make it optional with a defined valued RPG_HAS_OVERLOAD , see ILEvator https://github.com/sitemule/ILEvator/blob/main/headers/ilevator.rpgle#L1327

We need reasonable names for exported procedure (regardless of overloading):
il_cors_addCorsConfiguration1 -> il_cors_addCorsConfigurationValues
il_cors_addCorsConfiguration2 -> il_cors_addCorsConfigurationCustomHandler

ILEDocs format is not correct. The format should be like this:

```
///
// <title>
//
// <description>
//
// @param <just the description of the parameter, no parameter name needed>
// @return <return value description>
///
```

See https://bitbucket.org/m1hael/iledocs/wiki/ILEDocs_Syntax

Service program signature should only include the major version of the version number. Changes in the minor version should be compatible to the previous version and thus doesn't need a change in the signature.  CORS 2.0.0 => CORS 2
We don't need a version history in the service program signatures.

**Comment by rgala** [comment]
Signature history is to maintain backwards compatibility. Are you sure you do not want it?

**Comment by m1h43l** [comment]
> Signature history is to maintain backwards compatibility. Are you sure you do not want it?

The new signature should be "CORS 2" , major number of the version number is sufficient.

The previous signature can be included to remain backwards compatibility.

What I meant with "no history" is that we don't need a new signature for every new feature added to the service program if the new version is compatible with the old. If we have

- CORS 2
- CORS 1.0.1

Then we don't need

- CORS 2.1
- CORS 2
- CORS 1.0.1

We can just keep:

- CORS 2
- CORS 1.0.1

If we have a breaking change than we just replace all signatures with the new one (as it is no longer compatible):

- CORS 3

I hope that clears things up.

**Comment by rgala** [comment]
If you want the code to be compatible with older versions then maybe TGTRLS should be set to a minimum version you want to support?

**Comment by rgala** [comment]
OVERLOAD and SND-MSG are available in 7.3, but not 7.2. Please confirm it has to be 7.2 compatible.

**Comment by m1h43l** [comment]
7.3 is ok for the plugins.

**Comment by m1h43l** [comment]
Looks good 👍 🙂 !

Perhaps you can add an example on how to add a CORS configuration and one example on how to write a custom handler?

**Comment by rgala** [comment]
I have created a PR with readme file

**Pull request merged**
