### PR TITLE
fixed parsing of query string

### PR DESCRIPTION
**Pull request by m1h43l**
The function `il_getRequestQueryString` returned not the query string (it returned too much). The length of the query string was not set right. Also the ? character should not be included in the query string value as it doesn't add any value.

I added some unit tests for testing the parsing of the query string.

### CODE REVIEW

**Comment by m1h43l** [comment]
Added a fix for parsing the resource.  When the URL includes a query string then the ? character was included in the resource path which it really shouldn't.

Added some unit tests for testing the fix.

**Comment by NielsLiisberg** [comment]
Great job!!

**Comment by m1h43l** [comment]
Thanks. What I noticed is that the setup of the makefile is not very dev-friendly for those fixing bugs because at the moment I need to compile _all_ modules even if I just need to compile just one. I would vote to have for each module an extra target.

**Comment by NielsLiisberg** [comment]
Than you for your feedback !!

Take a look at the .vscode task files. There you can see that separate modules are supported.. However - I did not put to much attention in the makefile - I have therefor remade the makefile for the examples ... but not for the service program yet ...

**Pull request merged**
